export const BASE_API_URL = 'http://localhost:8080';
export const REGISTER_SCHOOL_URL = BASE_API_URL + '/auth/signup/school';
export const REGISTER_USER_URL = BASE_API_URL + '/auth/signup/user';
export const LOGIN_URL = BASE_API_URL + '/auth/signin';
export const ALL_EVENTS_URL = BASE_API_URL + "/event/all";
export const GET_EVENT_BY_DISECODE_URL = BASE_API_URL + "/event/school/";
export const CREATE_EVENT_BY_DISECODE_URL = BASE_API_URL + "/event/create/"; 
export const PARTICIPATE_EVENT_URL = BASE_API_URL + "/participation/add/";
export const SCHOOL_LIST_URL = BASE_API_URL + "/school/all";
export const SCHOOL_URL = BASE_API_URL + '/school/get/';
export const USER_PROFILE_URL = BASE_API_URL + '/user/';
export const POST_EVENT_IMAGE_URL = BASE_API_URL + '/event/image/';
export const GET_EVENT_IMAGE_URL = BASE_API_URL + '/event/getImage/';
export const TRANSFERS_URL = BASE_API_URL + '/transfer/all/';
export const ACCEPT_TRANSFERS_URL = BASE_API_URL + '/transfer/accept/';
export const REJECT_TRANSFERS_URL = BASE_API_URL + '/transfer/reject/';
export const PARTICIPATIONS_OF_USER_URL = BASE_API_URL + '/participation/all/';
export const UNPARTICIPATED_EVENTS_OF_USER_URI = BASE_API_URL + 'event/unparticipated/'
